[cosmic-ray]
# What to mutate: your package dir under src/
module-path = ["src/calista"]
timeout = 60.0
test-runner = "pytest"
test-command = "pytest -q"


# Use the local distributor & subprocess execution (simple, reliable)
[cosmic-ray.distributor]
name = "local"
worker-count = 1

[cosmic-ray.execution-engine]
name = "subprocess"

# Ensure src is on sys.path in subprocesses
[cosmic-ray.environment]
variables = { PYTHONPATH = "src" }

# Optional: focus on specific packages/modules
[cosmic-ray.targets]
# Mutate only your code, not third-party libs
include = ["calista.*"]

# Optional: only mutate lines that differ from main
[cosmic-ray.filters.git-filter]
branch = "origin/main"

[cosmic-ray.filters.operators-filter]
exclude-operators = ["core/ReplaceBinaryOperator_BitOr_.*"]


# Optional: badge look & thresholds (used by cr-badge)
[cosmic-ray.badge]
label = "mutation"
format = "%.1f %%"
[cosmic-ray.badge.thresholds]
50  = "red"
70  = "orange"
90  = "yellow"
101 = "green"
