site_name: CALISTA
site_description: CCD processing & photometry with event sourcing
site_url: https://mhallum.github.io/calista
repo_url: https://github.com/mhallum/calista
repo_name: mhallum/calista
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.follow
  palette:
    scheme: default
nav:
  - Home: index.md
  - ADRs:
      - "ADR 0001: Use Event Sourcing": adr/0001-use-event-sourcing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mhallum/calista
