site_name: CALISTA
site_description: CCD processing & photometry with event sourcing
site_url: https://mhallum.github.io/calista
repo_url: https://github.com/mhallum/calista
repo_name: mhallum/calista

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/typography.css

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/dev/gen_api_nav.py # generates docs/dev/api/SUMMARY.md and docs/dev/api/**
  - literate-nav:
      nav_file: docs/dev/api/SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            extensions:
              - griffe_inherited_docstrings
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mhallum/calista

nav:
  - Home: index.md
  - User Guide:
      - Overview: user/index.md
      - Installation:
          - Database: user/install/database.md
        # - Configuration: user/configuration.md
  - Developer Guide:
      - Overview: dev/index.md
      - Database:
          - "Migrations Policy": dev/db/migrations.md
          - "Event Store Schema Overview": dev/db/eventstore_schema.md
      - Testing:
          - "Event Store Testing": dev/testing/eventstore.md
      - API: dev/api/SUMMARY.md # generated by gen_api_nav.py
      - ADRs:
          - "ADR 0001: Use Event Sourcing": dev/adr/0001-use-event-sourcing.md
          - "ADR 0002: Content-Addressed File Store (CAS)": dev/adr/0002-cas-file-store.md
          - "ADR 0003: Database": dev/adr/0003-database.md
          - "ADR 0004: Schema Migrations": dev/adr/0004-schema-migrations.md
          - "ADR 0005: Event Store": dev/adr/0005-event-store.md
          - "ADR 0006: Event Envelope": dev/adr/0006-event-envelope.md
          - "ADR 0007: Identifiers (UUID vs ULID)": dev/adr/0007-identifiers.md
          - "ADR 0008: Concurrency & Versioning": dev/adr/0008-concurrency-and-versioning.md
          - "ADR 0009: Timekeeping": dev/adr/0009-timekeeping.md
          - "ADR 0010: Retention & Archival": dev/adr/0010-retention-and-archival.md
          - "ADR 0011: File Store Integration": dev/adr/0011-filestore-integration.md
          - "ADR 0012: Domain vs Integration Events": dev/adr/0012-domain-vs-integration-events.md
          - "ADR 0013: Querying & Projections": dev/adr/0013-querying-and-projections.md
          - "ADR 0014: Event Store Testing Strategy": dev/adr/0014-eventstore-testing-strategy.md
          - "ADR 0015: Mutation Testing Policy (Cosmic Ray)": dev/adr/0015-mutation-testing-policy.md
          - "ADR 0016: Adopt Mutmut for Mutation Testing (supersedes Cosmic Ray)": dev/adr/0016-adopt-mutmut-for-mutation-testing.md
          - "ADR 0017: Remove Mutation Testing from CI (Mutmut remains optional)": dev/adr/0017-remove-mutation-testing-from-ci.md
